### ISSUE TITLE
Skeleton analysis breaks in `cf.ProduceColumns` task

### ISSUE THREAD

**Issue by pkausw** [columnflow/columnflow#290]
When we setup a new analysis with columnflow following the [Quickstart](https://github.com/columnflow/columnflow#quickstart) instructions, there is a bug in the `cf.ProduceColumns` task (originally found by Tom Davids). I was able to reproduce the error and see the following:

```
law run cf.PlotVariables1D --version dev1 --datasets tt_sl_powheg --variables jet1_pt --branch 0

# lots of information about task chain here ...

=============================== entering sandbox ===============================
task   : cf.ProduceColumns_h4l_config_analy_0__4e44177d8c
sandbox: bash::$CF_BASE/sandboxes/venv_columnar_dev.sh
================================================================================

INFO: luigi-interface - Informed scheduler that task   cf.ProduceColumns_h4l_config_analy_0__4e44177d8c   has status   PENDING
INFO: luigi-interface - Done scheduling tasks
INFO: luigi-interface - Running Worker with 1 processes
INFO: luigi-interface - [pid 6761] Worker Worker(salt=8813480614, workers=4, host=naf-cms11.desy.de, username=pkeicher, pid=6587) running   cf.ProduceColumns(effective_workflow=local, branch=0, analysis=h4l.config.analysis_h4l.analysis_h4l, version=dev1, config=run2_2017_nano_v9, shift=nominal, local_shift=nominal, dataset=tt_sl_powheg, calibrators=example, selector=example, producer=example)
ERROR: luigi-interface - [pid 6761] Worker Worker(salt=8813480614, workers=4, host=naf-cms11.desy.de, username=pkeicher, pid=6587) failed    cf.ProduceColumns(effective_workflow=local, branch=0, analysis=h4l.config.analysis_h4l.analysis_h4l, version=dev1, config=run2_2017_nano_v9, shift=nominal, local_shift=nominal, dataset=tt_sl_powheg, calibrators=example, selector=example, producer=example)
Traceback (most recent call last):
  File "/nfs/dust/cms/user/pkeicher/cf_cache/software/venvs/venv_columnar_dev_3cbb5aff/lib/python3.9/site-packages/luigi/worker.py", line 203, in run
    new_deps = self._run_get_new_deps()
  File "/nfs/dust/cms/user/pkeicher/cf_cache/software/venvs/venv_columnar_dev_3cbb5aff/lib/python3.9/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/nfs/dust/cms/user/pkeicher/uhh/podas/hto4l/modules/columnflow/modules/law/law/decorator.py", line 244, in wrapper
    return decorator(fn, _opts, *args, **kwargs)
  File "/nfs/dust/cms/user/pkeicher/uhh/podas/hto4l/modules/columnflow/modules/law/law/decorator.py", line 270, in log
    return fn(task, *args, **kwargs)
  File "/nfs/dust/cms/user/pkeicher/uhh/podas/hto4l/modules/columnflow/modules/law/law/decorator.py", line 244, in wrapper
    return decorator(fn, _opts, *args, **kwargs)
  File "/nfs/dust/cms/user/pkeicher/uhh/podas/hto4l/modules/columnflow/modules/law/law/decorator.py", line 519, in localize
    return fn(task, *args, **kwargs)
  File "/nfs/dust/cms/user/pkeicher/uhh/podas/hto4l/modules/columnflow/modules/law/law/decorator.py", line 231, in wrapper
    result = call(state)
  File "/nfs/dust/cms/user/pkeicher/uhh/podas/hto4l/modules/columnflow/modules/law/law/decorator.py", line 301, in call
    return fn(task, *args, **kwargs)
  File "/nfs/dust/cms/user/pkeicher/uhh/podas/hto4l/modules/columnflow/columnflow/tasks/production.py", line 86, in run
    reader_targets = self.producer_inst.run_setup(reqs["producer"], inputs["producer"])
  File "/nfs/dust/cms/user/pkeicher/uhh/podas/hto4l/modules/columnflow/columnflow/columnar_util.py", line 2147, in run_setup
    dep.run_setup(reqs, inputs, reader_targets, _cache=_cache)
  File "/nfs/dust/cms/user/pkeicher/uhh/podas/hto4l/modules/columnflow/columnflow/columnar_util.py", line 2141, in run_setup
    self.setup_func(reqs, inputs, reader_targets)
  File "/nfs/dust/cms/user/pkeicher/uhh/podas/hto4l/modules/columnflow/columnflow/production/normalization.py", line 94, in normalization_weights_setup
    int(process_id) for process_id in selection_stats["sum_mc_weight_per_process"]
KeyError: 'sum_mc_weight_per_process'
```

As you can see, columnflow expects the keyword `sum_mc_weight_per_process`, which needs to be added by the analysis itself (see e.g. [this](https://github.com/uhh-cms/hh2bbtautau/blob/master/hbt/production/weights.py#L70-L100) example). Consequently, new analyses will not run correctly out of the box.

The keyword is required for normalization of weights, which is definitely analysis specific. But maybe we should either

- make it optional in the cf backend - afterall, it's not strictly required (though needed in many cases depending on the MC sample and analysis), or
-  add a line of code to the example producer in the analysis skeleton that produces a dummy entry

What do you think @riga @mafrahm ?

**Comment by riga** [comment]
The fix was actually pushed as part of https://github.com/columnflow/columnflow/pull/285, so can close this issue.

@tolange There is a message printed now after setting up the `cms_minimal` example stating that access to files on /afs/cern.ch is required.
