### ISSUE TITLE
MemoryError: std::bad_alloc in CreateHistograms step :: SKELETON ANALYSIS

### ISSUE THREAD

**Issue by gsaha009** [columnflow/columnflow#294]
Following the discussions in #290 and #291, I tried to run the skeleton analysis multiple times in lxplus 7 & 8 (also in local cluster) using datasets `st_tchannel_t_powheg` & `dy_lep_2j_amcatnlo`. 90% of the times, I got a memory error: 
```sh
ERROR: luigi-interface - [pid 18586] Worker Worker(salt=3353233402, workers=1, host=sbgui3.in2p3.fr, username=gsaha, pid=18432) failed    cf.CreateHistograms(effective_workflow=local, branch=0, analysis=hcp.config.analysis_hcp.analysis_hcp, version=dev0, config=run2_2017_nano_v9, shift=nominal, local_shift=nominal, dataset=st_tchannel_t_powheg, calibrators=example, selector=example, producers=example, variables=jet1_eta)
Traceback (most recent call last):
  File "/home/gsaha/Work/ColumnflowAnalyses/HCPToTauTau/data/software/venvs/cf_dev_9b04c75c/lib/python3.9/site-packages/luigi/worker.py", line 203, in run
    new_deps = self._run_get_new_deps()
  File "/home/gsaha/Work/ColumnflowAnalyses/HCPToTauTau/data/software/venvs/cf_dev_9b04c75c/lib/python3.9/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/gsaha/Work/ColumnflowAnalyses/HCPToTauTau/modules/columnflow/modules/law/law/decorator.py", line 244, in wrapper
    return decorator(fn, _opts, *args, **kwargs)
  File "/home/gsaha/Work/ColumnflowAnalyses/HCPToTauTau/modules/columnflow/modules/law/law/decorator.py", line 270, in log
    return fn(task, *args, **kwargs)
  File "/home/gsaha/Work/ColumnflowAnalyses/HCPToTauTau/modules/columnflow/modules/law/law/decorator.py", line 244, in wrapper
    return decorator(fn, _opts, *args, **kwargs)
  File "/home/gsaha/Work/ColumnflowAnalyses/HCPToTauTau/modules/columnflow/modules/law/law/decorator.py", line 519, in localize
    return fn(task, *args, **kwargs)
  File "/home/gsaha/Work/ColumnflowAnalyses/HCPToTauTau/modules/columnflow/modules/law/law/decorator.py", line 231, in wrapper
    result = call(state)
  File "/home/gsaha/Work/ColumnflowAnalyses/HCPToTauTau/modules/columnflow/modules/law/law/decorator.py", line 301, in call
    return fn(task, *args, **kwargs)
  File "/home/gsaha/Work/ColumnflowAnalyses/HCPToTauTau/modules/columnflow/columnflow/tasks/histograms.py", line 233, in run
    histograms[var_key].fill(**{field: arrays[field] for field in arrays.fields})
  File "/home/gsaha/Work/ColumnflowAnalyses/HCPToTauTau/data/software/venvs/venv_columnar_dev_3cbb5aff/lib/python3.9/site-packages/hist/basehist.py", line 232, in fill
    return super().fill(*args, *data, weight=weight, sample=sample, threads=threads)
  File "/home/gsaha/Work/ColumnflowAnalyses/HCPToTauTau/data/software/venvs/venv_columnar_dev_3cbb5aff/lib/python3.9/site-packages/boost_histogram/_internal/hist.py", line 529, in fill
    self._hist.fill(*args_ars, weight=weight_ars, sample=sample_ars)  # type: ignore[arg-type]
MemoryError: std::bad_alloc
INFO: luigi-interface - Informed scheduler that task   cf.CreateHistograms_hcp_config_analy_0__3cfaa8453d   has status   FAILED
```
and for the rest, I found empty plots at the end. 

I see a lot of recent commits made even in an hour or two. So, this might already be in your agenda. 
This is the working area you might want to take a look: `/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/HCPToTauTau`. Please let me know if you need more info.

N.B: **Is there any `mattermost` channel for `columnflow / law / order`? For small discussions, maybe it will be useful rather than writing here? ...**

Thank you very much.

Gourab

**Comment by riga** [comment]
Hi @gsaha009 ,

we're seeing similar issues at various other places right now and we identified updates in upstream software packages as the source of the issue. In your particular case, it's due to a change between awkward 2.3.1 and 2.3.3 that I haven't pinpointed yet to open an ticket with the awkward developers.

In the sandboxes, so far we declared versions via the "compatible release" syntax `~=` (same as ), for instance

https://github.com/columnflow/columnflow/blob/76d4b0bed8a7037c4c13263db0a76b5abbe97f1a/sandboxes/columnar.txt#L3-L5

meaning that we tested it with the version that we put in the requirement file, but we allow for updates in case they are compatible. However, as you may now, some of these packages are also undergoing some developments these days, and I occasionally happens that a bug makes it through to one of their releases.

To not pass these issues down for users to find out through columnflow, I just pinned some of our dependencies back to exact versions that have been previously tested by us, e.g.

https://github.com/columnflow/columnflow/blob/98d94d4a7c86666c8115d96124c4c822bc0ee10d/sandboxes/columnar.txt#L3-L6

Can you check if this fixes the issue for you? A quick way to test would be to

- open a fresh shell and switch to your template analysis directory (do not source yet)
- go to the columnflow submodule, and `git pull`
- in your template analysis, do `CF_REINSTALL_SOFTWARE=1 source setup.sh <your_setup_name_if_you_used_one>`
- and then `law run` the same command as before, but with a different `--version` to make sure you're creating new files.

I'm testing the same thing in parallel on my end.

<hr />

Regarding the mattermost / slack channel, we already considered this and it might be a good platform for quick questions, but it's usually hard for new users to find previously asked questions there. We will discuss this this again internally and let you know :+1:

**Comment by gsaha009** [comment]
Hi @riga 
Thank you very much for your detailed response. I performed the steps you proposed and its working like a charm...  👯 
Gourab
