### ISSUE TITLE
XML parsing error

### ISSUE THREAD

**Issue by nprouvost** [columnflow/columnflow#401]
While trying to use the GetDatasetLFNS task on the newly custom processed 2016 post VFP samples, I came across the following error with the webdav protocol:

```
ERROR: luigi-interface - [pid 33893] Worker Worker(salt=828108699, workers=1, host=naf-cms11.desy.de, username=prouvost, pid=33893) failed    cf.GetDatasetLFNs(source_path=NO_STR, analysis=hbt.config.analysis_hbt.analysis_hbt, config=run2_2016_nano_uhh_v12_limited, shift=nominal, local_shift=nominal, dataset=tt_sl_powheg, replicas=5)
Traceback (most recent call last):
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/modules/columnflow/modules/law/law/target/remote/interface.py", line 120, in wrapper
    return func(self, *args, **kwargs)
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/modules/columnflow/modules/law/law/contrib/gfal/target.py", line 355, in filecopy
    raise e
law.contrib.gfal.target.GFALError_filecopy: DESTINATION MAKE_PARENT   Result XML Parsing Error: XML parse error at line 2: Extra content at the end of the document\n after 1 attempts (GFALError_filecopy: unknown reason)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/modules/columnflow/modules/law/law/target/remote/interface.py", line 126, in wrapper
    e.reraise()
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/modules/columnflow/modules/law/law/target/remote/interface.py", line 35, in reraise
    return six.reraise(self.exc_type, self.exc_value, self.exc_traceback)
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/software/venvs/cf_dev_9b04c75c/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/modules/columnflow/modules/law/law/contrib/gfal/target.py", line 349, in filecopy
    ctx.filecopy(params, src_uri, dst_uri)
gfal2.GError: DESTINATION MAKE_PARENT   Result XML Parsing Error: XML parse error at line 2: Extra content at the end of the document\n after 1 attempts

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/software/venvs/cf_dev_9b04c75c/lib/python3.9/site-packages/luigi/worker.py", line 203, in run
    new_deps = self._run_get_new_deps()
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/software/venvs/cf_dev_9b04c75c/lib/python3.9/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/modules/columnflow/modules/law/law/decorator.py", line 244, in wrapper
    return decorator(fn, _opts, *args, **kwargs)
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/modules/columnflow/modules/law/law/decorator.py", line 272, in log
    return fn(task, *args, **kwargs)
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/modules/columnflow/columnflow/tasks/external.py", line 118, in run
    self.transfer(tmp)
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/modules/columnflow/modules/law/law/contrib/tasks/__init__.py", line 121, in transfer
    replica.copy_from_local(src_path, cache=False)
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/modules/columnflow/modules/law/law/target/remote/base.py", line 611, in copy_from_local
    return self.copy_from(src, **kwargs)
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/modules/columnflow/modules/law/law/target/file.py", line 325, in copy_from
    return self.fs.copy(get_path(src), self.path, perm=perm, dir_perm=dir_perm, **kwargs)
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/modules/columnflow/modules/law/law/target/remote/base.py", line 500, in copy
    return self._cached_copy(src, dst, perm=perm, **kwargs)
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/modules/columnflow/modules/law/law/target/remote/base.py", line 405, in _cached_copy
    return self._atomic_copy(src, dst, perm=perm, validate=validate, **kwargs)
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/modules/columnflow/modules/law/law/target/remote/base.py", line 357, in _atomic_copy
    src_uri, dst_uri = self.file_interface.filecopy(src, dst, **kwargs)
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/modules/columnflow/modules/law/law/target/remote/interface.py", line 142, in wrapper
    six.reraise(e_type, e_type(msg, *e.args[1:]), traceback)
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/software/venvs/cf_dev_9b04c75c/lib/python3.9/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/modules/columnflow/modules/law/law/target/remote/interface.py", line 126, in wrapper
    e.reraise()
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/modules/columnflow/modules/law/law/target/remote/interface.py", line 35, in reraise
    return six.reraise(self.exc_type, self.exc_value, self.exc_traceback)
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/software/venvs/cf_dev_9b04c75c/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/afs/desy.de/user/p/prouvost/xxl/af-cms/hh2bbtautau/modules/columnflow/modules/law/law/contrib/gfal/target.py", line 349, in filecopy
    ctx.filecopy(params, src_uri, dst_uri)
gfal2.GError: DESTINATION MAKE_PARENT   Result XML Parsing Error: XML parse error at line 2: Extra content at the end of the document\n after 1 attempts
function: GFALFileInterface.filecopy
attempts: 2
args    : ('file:///tmp/luigi-tmp-859199924', '/analysis_hbt/cf.GetDatasetLFNs/run2_2016_nano_uhh_v12_limited/tt_sl_powheg/nominal/lfns_6484a2293f.0.json')
kwargs  : {'base': 'davs://dcache-cms-webdav-wan.desy.de:2880/pnfs/desy.de/cms/tier2/store/user/nprouvos/hbt_store'}
error   : GError: 'DESTINATION MAKE_PARENT   Result XML Parsing Error: XML parse error at line 2: Extra content at the end of the document\n after 1 attempts'
```

Interestingly, if I change the protocol to gsiftp in the law.cfg file, this error does not occur and the task works fine. However, not being able to use webdav is very annoying for further tasks, as you are not able to process more than a few HTcondor jobs at once for example. Therefore, I would like to ask if a fix might be possible?

For completeness, the list of packages used in the corresponding sandbox:
```
pip freeze
asttokens==2.4.1
conda-pack @ file:///home/conda/feedstock_root/build_artifacts/conda-pack_1691435290924/work
coverage==7.4.1
decorator==5.1.1
docutils==0.20.1
exceptiongroup==1.2.0
executing==2.0.1
flake8==5.0.4
flake8-commas==2.1.0
flake8-quotes==3.3.2
gfal2-python @ file:///home/conda/feedstock_root/build_artifacts/python-gfal2_1696195348860/work
gfal2-util @ file:///home/conda/feedstock_root/build_artifacts/gfal2-util_1702401554273/work
iniconfig==2.0.0
ipython==8.18.1
jedi==0.19.1
lockfile==0.12.2
luigi==3.4.0
matplotlib-inline==0.1.6
mccabe==0.7.0
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1707225342954/work/dist/numpy-1.26.4-cp39-cp39-linux_x86_64.whl#sha256=c799942b5898f6e6c60264d1663a6469a475290e758c654aeeb78e2596463abd
packaging==23.2
parso==0.8.3
pexpect==4.9.0
pipdeptree==2.13.2
pluggy==1.4.0
prompt-toolkit==3.0.43
ptyprocess==0.7.0
pure-eval==0.2.2
pycodestyle==2.9.1
pyflakes==2.5.0
Pygments==2.17.2
pytest==7.4.4
pytest-cov==3.0.0
python-daemon==3.0.1
python-dateutil==2.8.2
PyYAML==6.0.1
scinum==2.0.2
six==1.16.0
stack-data==0.6.3
tenacity==8.2.3
tomli==2.0.1
tornado==6.4
traitlets==5.14.1
typing_extensions==4.8.0
wcwidth==0.2.13
xrootd @ file:///home/conda/feedstock_root/build_artifacts/xrootd_1706189722120/work/build-dir/bindings/python
```
The gfal2 version is 1.12.0 (obtained through import and using the __version__ attribute)

**Comment by nprouvost** [comment]
Addendum: 
After trying to test again with webdav for tasks further down the task tree, I could observe that the tasks which are finished and marked as done with gsiftp get shown again as pending when switching the base in the law.cfg back to webdav. Therefore, there seems to be a fundamental problem in the paths through webdav or the access of webdav to the directories.

**Comment by nprouvost** [comment]
@pkausw Here the micromamba environment:

channels:
- conda-forge
dependencies:
- _libgcc_mutex=0.1=conda_forge
- _openmp_mutex=4.5=2_gnu
- bash=5.2.21=h7f99829_0
- bzip2=1.0.8=hd590300_5
- c-ares=1.26.0=hd590300_0
- ca-certificates=2024.2.2=hbcca054_0
- cgsi-gsoap=1.3.11=h8bf5a6f_7
- conda-pack=0.7.1=pyhd8ed1ab_0
- curl=8.5.0=hca28451_0
- cyrus-sasl=2.1.27=h54b06d7_7
- davix=0.8.5=h3299534_0
- dcap=2.47.14=hc03aca7_1
- expat=2.5.0=hcb278e6_1
- gct=6.2.1629922860=h9f628fe_3
- gettext=0.21.1=h27087fc_0
- gfal2=2.21.3=h670dfc4_0
- gfal2-util=1.8.1=pyhd8ed1ab_0
- git=2.43.0=pl5321h7bc287a_0
- git-lfs=3.4.1=ha770c72_0
- gsoap=2.8.123=h8dc497d_0
- icu=73.2=h59595ed_0
- json-c=0.16=hc379101_0
- keyutils=1.6.1=h166bdaf_0
- krb5=1.21.2=h659d440_0
- ld_impl_linux-64=2.40=h41732ed_0
- libblas=3.9.0=21_linux64_openblas
- libboost=1.82.0=h6fcfa73_6
- libboost-python=1.82.0=py39hda80f44_6
- libcblas=3.9.0=21_linux64_openblas
- libcurl=8.5.0=hca28451_0
- libedit=3.1.20191231=he28a2e2_2
- libev=4.33=hd590300_2
- libexpat=2.5.0=hcb278e6_1
- libffi=3.4.2=h7f98852_5
- libgcc=7.2.0=h69d50b8_2
- libgcc-ng=13.2.0=h807b86a_5
- libgfortran-ng=13.2.0=h69a702a_5
- libgfortran5=13.2.0=ha4646dd_5
- libglib=2.78.3=h783c2da_0
- libgomp=13.2.0=h807b86a_5
- libiconv=1.17=hd590300_2
- liblapack=3.9.0=21_linux64_openblas
- libnghttp2=1.58.0=h47da74e_1
- libnsl=2.0.1=hd590300_0
- libntlm=1.4=h7f98852_1002
- libopenblas=0.3.26=pthreads_h413a1c8_0
- libsqlite=3.44.2=h2797004_0
- libssh2=1.11.0=h0841786_0
- libstdcxx-ng=13.2.0=h7e041cc_5
- libtool=2.4.7=h27087fc_0
- libuuid=2.38.1=h0b41bf4_0
- libxcrypt=4.4.36=hd590300_1
- libxml2=2.12.5=h232c23b_0
- libzlib=1.2.13=hd590300_5
- myproxy=6.2.14=h3ca6c24_3
- ncurses=6.4=h59595ed_2
- numpy=1.26.4=py39h474f0d3_0
- openldap=2.6.7=h0bac7fd_0
- openssl=3.2.1=hd590300_0
- pcre=8.45=h9c3ff4c_0
- pcre2=10.42=hcad00b1_0
- perl=5.32.1=7_hd590300_perl5
- pip=24.0=pyhd8ed1ab_0
- pugixml=1.11.4=h59595ed_1
- python=3.9.18=h0755675_1_cpython
- python-gfal2=1.12.0=py39hd8ed99e_3
- python_abi=3.9=4_cp39
- readline=8.2=h8228510_1
- scitokens-cpp=1.0.2=haea88ab_0
- setuptools=69.0.3=pyhd8ed1ab_0
- srm-ifce=1.24.6=h47532b5_1
- tk=8.6.13=noxft_h4845f30_101
- tzdata=2024a=h0c530f3_0
- voms=2.1.0rc3=h25bd2b9_0
- wheel=0.42.0=pyhd8ed1ab_0
- xrootd=5.6.6=py39h2326971_0
- xz=5.2.6=h166bdaf_0
- zlib=1.2.13=hd590300_5
- zsh=5.8=h3d38e88_1
- zstd=1.5.5=hfc55251_0

**Comment by nprouvost** [comment]
So, following https://github.com/conda-forge/davix-feedstock/commit/c0b5bfe1f314dcd5fdddad3a519b8d3871c98f38, an issue between the davix version and libxml2 version was solved. Therefore, updating your davix version with `micromamba install davix==0.8.6` or `micromamba install davix==0.8.5=h5f3b820_1` should solve the problem.

**Comment by nprouvost** [comment]
As the packages used seem to have updated this too, reinstalling the software stack with "CF_REINSTALL_SOFTWARE=1 source setup.sh YOUR_ENV_NAME" should also work.
