### ISSUE TITLE
columnflow setup for slurm cluster

### ISSUE THREAD

**Issue by JohanWulff** [columnflow/columnflow#418]
Dear Columnflow Developers, 

I am trying to run the [hh2bbtautau](https://github.com/uhh-cms/hh2bbtautau) analysis using a slurm scheduler that connects to a cluster at my institute.  When running tasks with the `--workflow slurm` parameter set, I run into this error: `sbatch: error: invalid partition specified: cms-uhh`. The corresponding job script contains the following line causing this:

```
#SBATCH --partition=cms-uhh
```
I cannot find where this parameter is set in columnflow. This partition is clearly uhh-specific and I'd have to change it but I cannot find where. Any pointer would be appreciated.

**Comment by pkausw** [comment]
Thanks for raising this issue @JohanWulff ! The remote workflows are managed by law, so I'm tagging @riga as well. Have you checked your law installation as well when you looked for the uhh specific line?

**Comment by pkausw** [comment]
Ah very good! The code actually looks like you _can_ overwrite this by setting the appropiate environment variables, see https://github.com/columnflow/columnflow/blob/c8516a5cccf23475830e998165ce7a478f35f2ef/setup.sh#L326-L328. The one you are after would be `CF_SLURM_PARTITION`.

You can add this to your shell script in `.setups/YOURSETUPNAME.sh` so it will always be source automatically when you source your analysis setup script. Can you try this?

**Comment by JohanWulff** [comment]
thanks @pkausw -- the overriding of the variable works in principle. I'm stuck with a slurm-related submit error but that doesn't have anything to do with columnflow anymore. Looking at the default of `cf_slurm_flavor` which is `maxwell`, I was also under the impression I'd have to change this since I obv. don't have access to maxwell from my institute. Changing that causes law to complain though, saying that my choice of `cf_slurm_flavor` is not a valid choice from `{maxwell}`. Is this desired? This happens because the possible choices for this parameter are defined in [columnflow/columnflow/tasks/framework/remote.py](https://github.com/columnflow/columnflow/blob/c8516a5cccf23475830e998165ce7a478f35f2ef/columnflow/tasks/framework/remote.py#L701) as: `("maxwell")`

**Comment by pkausw** [comment]
Hm, that is indeed a shame :/ What happens if you add your choice of slurm flavor to the list? I'm not entirely sure how law will react to this of course, but might be worth trying nonetheless

**Comment by pkausw** [comment]
Hi @JohanWulff , are there any updated regarding this? Were you able to resolve the issue?

If yes, we might want to think about remove the choices for this particular parameter or at least ammend the list of supported options. It would be very interesting what you added to the choices to move on with this!

**Comment by JohanWulff** [comment]
Not yet sorry. I'll try to understand how the submission is handled here at our scheduler to be able to test it properly and close this issue soon.

**Comment by pkausw** [comment]
Hi @JohanWulff , it's been a while - any updates regarding this issue?

**Comment by JohanWulff** [comment]
Hi @pkausw 
sorry for taking so long on this.. i wasn't really working on this the past weeks. What makes it hard for me to see if this works in principle is the fact that i cannot get the slurm submission via columnflow to work but it seems like just passing a different `CF_SLURM_PARTITION` doesn't do it. 
Feel free to close this issue because at this point it's about understanding how the submission at our local cluster works more than anything.

**Comment by gsaha009** [comment]
Hi @pkausw and all,

Reopening this issue:

I was trying to use `slurm` in my institute cluster too, and unfortunately, it is not working. Can you or anyone please let me know what are the things that one should modify in order to use slurm? The problem I am getting is the following:

```sh
ERROR: luigi-interface - Luigi unexpected framework error while scheduling cf.SelectEvents(effective_workflow=slurm, branch=-1, analysis=httcp.config.analysis_httcp.analysis_httcp, version=debug, config=run3_2022_preEE_nano_cp_tau_v12_limited, shift=nominal, local_shift=nominal, dataset=dy_lep_m50_madgraph, calibrators=main, selector=main, workflow=slurm)
Traceback (most recent call last):
  File "/opt/cms/ui5_data1/gsaha/data/software/venvs/cf_dev_9b04c75c/lib/python3.9/site-packages/luigi/worker.py", line 806, in add
    for next in self._add(item, is_complete):
  File "/opt/cms/ui5_data1/gsaha/data/software/venvs/cf_dev_9b04c75c/lib/python3.9/site-packages/luigi/worker.py", line 918, in _add
    resources=task.process_resources(),
  File "/home/gsaha/Work/ColumnflowAnalyses/CPinHToTauTau/modules/columnflow/modules/law/law/workflow/remote.py", line 1561, in process_resources
    resources = self.workflow_proxy.process_resources()
  File "/home/gsaha/Work/ColumnflowAnalyses/CPinHToTauTau/modules/columnflow/modules/law/law/workflow/remote.py", line 544, in process_resources
    get_job_resources = self._get_task_attribute("job_resources")
  File "/home/gsaha/Work/ColumnflowAnalyses/CPinHToTauTau/modules/columnflow/modules/law/law/workflow/base.py", line 101, in _get_task_attribute
    raise AttributeError("'{!r}' object has none of the requested attribute(s) {}".format(
AttributeError: 'SlurmWorkflowProxy(task=cf.SelectEvents_httcp_config_ana__1__2c58004c15)' object has none of the requested attribute(s) slurm_job_resources
INFO: luigi-interface - Worker Worker(salt=8313690224, workers=1, host=sbgui5.in2p3.fr, username=gsaha, pid=493053) was stopped. Shutting down Keep-Alive thread
ERROR: luigi-interface - Uncaught exception in luigi
```

Any suggestion would be very helpful
Thank you very much

Best,
Gourab

**Comment by gsaha009** [comment]
Hi again,

I have added a hook like HTCondor in `law/contrib/slurm/workflow.py`, and this error is gone :)
However, a different issue is there now, which is related to `sbatch: error: Batch job submission failed: Invalid account or account/partition combination specified`
I have already changed the `partition` name, but there are multiple partition, and I do not want to specify any name there. Is it possible?
But, I think I have to change this default `maxwell` flavor as well. Is there any possibility that law or columnflow can choose that automatically?
Thanks :)

**Comment by pkausw** [comment]
Hi @gsaha009 ,

glad to hear that you were able to make progress with this. Regarding the partition: Looking at the corresponding [law implementation](https://github.com/riga/law/blob/master/law/contrib/slurm/job.py#L65), it should be enough to simply set the partition to `None` (either via the law config or with a more manual implementation, e.g. in the `__init__` function).

Regarding automated resolution of the flavor: This is a good proposition. This mechanism for e.g. htcondor works via a naming scheme of the hosts that use a specific flavor. So it would require additional knowledge about your cluster that we don't have - but we're happy to work with you on a PR to implement this. In the meanwhile, we recommend to define the flavor in the law.cfg file.

Cheers,
Philip

**Comment by gsaha009** [comment]
Hi @pkausw 

I have found the partition name I am using in our cluster, and this problem is fixed now. But, there is new problem now.
I can send the jobs to our `slurm` cluster now, but because of the following reason, the jobs are getting failed.

```sh
-- setup -------------------------------------------------------------------------------------------

-- bootstrap file
run bootstrap file 'remote_bootstrap_b4f052643c.sh'

source repository setup ...
the CPinHToTauTau analysis was already succesfully setup
re-running the setup requires a new shell
setup failed with code 1 # HERE IT IS
bootstrap file failed (exit code 1), stop job

-- stageout ----------------------------------------------------------------------------------------

-- stageout file
stageout file empty, skip
```

I see the source setup lines in the `bootstrap` file twice.
The job was failed at [this level](https://github.com/columnflow/columnflow/blob/master/columnflow/tasks/framework/remote_bootstrap.sh#L147) before showing `remote_bootstrap_b4f052643c.sh: line 147: aklog: command not found`
It was written optional, so I commented that line, and the error message went away, and even if I comment out the [next one](https://github.com/columnflow/columnflow/blob/master/columnflow/tasks/framework/remote_bootstrap.sh#L155), the same error persists.

Let me know if you have any idea.
Thanks again


Gourab

**Comment by pkausw** [comment]
Hi @gsaha009 ,

this issue arises because some clusters are set up such that they forward your local environment variables to remote jobs. When you run `source setup.sh YOUR_SETUP`, we create a local variable `${YOUR_ANALYSIS_SHORTHAND}_SETUP` to denote whether the setup has already been run successfully before. It seems like your cluster is setup such that this flag is forwarded, which is why your remote job thinks that it's already setup - which is probably not exactly true.

There are two ways to fix this behavior:

- Disable the forwarding of your (custom) environment variables if possible. This would be the recommended way to fix the behavior since we also manipulate some (python) path environment variables, and doing so multiple times can have unforseen effects.
- Add the `cf_pre_setup_command` to the `[analysis]` section of your law config like this

```config
[analysis]
# define some custom commands before the remote job calls `source setup.sh YOUR_SETUP_NAME`.
# note that you need to replace `{YOUR_ANALYSIS_SHORTHAND}` with your analysis short hand
cf_pre_setup_command: "export {YOUR_ANALYSIS_SHORTHAND}_SETUP=0;"
```

Either of these should do the trick, let us know if you have issues remaining.

Cheers,
Philip

**Comment by gsaha009** [comment]
Hi @pkausw 
I have resumed working in this again. In order to keep the software compatible to our cluster, we had to make two changes already.

1. The job status can not be fetched from the host machine in our cluster. But it is possible to do from any slurm client machine. So, we are saving the `sacct` output in a file in order to read the details from it,
```py
logger.debug("query slurm accounting history with command '{}'".format(cmd))
f=open("/home-pbs/gsaha/slurm_interface/please_do_this.sh","w")
f.write(cmd)
f.close()
# Wait until the job is done
while True:
    time.sleep(1)
    if os.path.exists("/home-pbs/gsaha/slurm_interface/here_is_the_result_sir.txt"):
        break

    f=open("/home-pbs/gsaha/slurm_interface/here_is_the_result_sir.txt","r")
        out=f.read()
    f.close()
    out=out.strip()
```
instead of [this](https://github.com/riga/law/blob/1d82bd4b8b5f2d85098f6aacb83046b9ba08b587/law/contrib/slurm/job.py#L183-L194).

2. Added `slurm_job_resources` in `workflow.py`

3. Added these in `law.cfg`
```
slurm_flavor: $CF_SLURM_FLAVOR
slurm_partition: vo.sbg.in2p3.fr
```
4. From the two options you have suggested, I preferred the 2nd option, as it seems that I can handle it without the involvement from IT. I added these lines in my `law.cfg`
```
cf_pre_setup_command: "export httcp_SETUP=0;"
```


But in the end, I am getting the same error

```sh
-- task infos
task module   : columnflow.tasks.calibration
task family   : CalibrateEvents
task params   : --log-file=NO_STR --analysis=httcp.config.analysis_httcp.analysis_httcp --version=Jan14_v2 --config=run3_2022_preEE_nano_cp_tau_v14_limited --shift=nominal --dataset=wz --calibrator=main -
-check-finite-output=True --check-overlapping-inputs=False
branches      : 0
job workers   : 1
auto retry    : no
dashboard data: -

-- files in LAW_JOB_INIT_DIR
> pwd
/grid-mnt/home-pbs/gsaha/ColumnflowAnalyses/CPinHToTauTau/data/cf_store/analysis_httcp/cf.CalibrateEvents/run3_2022_preEE_nano_cp_tau_v14_limited/wz/nominal/calib__main/Jan14_v2
> ls -la
total 60
drwxr-xr-x. 3 gsaha 652  4096 Jan 14 22:48 .
drwxr-xr-x. 3 gsaha 652  4096 Jan 14 22:19 ..
drwx------. 2 gsaha 652  4096 Jan 14 22:48 job_S2ZRjDw6Ekpl
-rw-r--r--. 1 gsaha 652   586 Jan 14 22:48 slurm_jobs_0To1.json
-rw-r--r--. 1 gsaha 652 39084 Jan 14  2025 stdall_0To1.txt

-- link input files
link /iphc/home-pbs/gsaha/ColumnflowAnalyses/CPinHToTauTau/data/jobs/sub_cf.CalibrateEvents_httcp_config_ana__1__4e3cc4e675_946zvuxi2vt/remote_bootstrap_b4f052643c.sh
link /iphc/home-pbs/gsaha/ColumnflowAnalyses/CPinHToTauTau/data/jobs/sub_cf.CalibrateEvents_httcp_config_ana__1__4e3cc4e675_946zvuxi2vt/x509up_u10084_6eb055297a
link /iphc/home-pbs/gsaha/ColumnflowAnalyses/CPinHToTauTau/data/jobs/sub_cf.CalibrateEvents_httcp_config_ana__1__4e3cc4e675_946zvuxi2vt/krb5cc_10084_LVOJ1M_ecb5c29852

-- render input files
render /iphc/home-pbs/gsaha/ColumnflowAnalyses/CPinHToTauTau/data/jobs/sub_cf.CalibrateEvents_httcp_config_ana__1__4e3cc4e675_946zvuxi2vt/remote_bootstrap_b4f052643c.sh

-- files in LAW_JOB_HOME
> pwd
/grid-mnt/home-pbs/gsaha/ColumnflowAnalyses/CPinHToTauTau/data/cf_store/analysis_httcp/cf.CalibrateEvents/run3_2022_preEE_nano_cp_tau_v14_limited/wz/nominal/calib__main/Jan14_v2/job_S2ZRjDw6Ekpl
> ls -la
total 28
drwx------. 2 gsaha 652  4096 Jan 14 22:48 .
drwxr-xr-x. 3 gsaha 652  4096 Jan 14 22:48 ..
lrwxrwxrwx. 1 gsaha 652   161 Jan 14 22:48 krb5cc_10084_LVOJ1M_ecb5c29852 -> /iphc/home-pbs/gsaha/ColumnflowAnalyses/CPinHToTauTau/data/jobs/sub_cf.CalibrateEvents_httcp_config_ana__1__4e3cc4e675_946zvuxi2vt/krb5cc_10084_LVOJ1M_ecb5c29852
-rw-r--r--. 1 gsaha 652 10282 Jan 14 22:48 remote_bootstrap_b4f052643c.sh
lrwxrwxrwx. 1 gsaha 652   155 Jan 14 22:48 x509up_u10084_6eb055297a -> /iphc/home-pbs/gsaha/ColumnflowAnalyses/CPinHToTauTau/data/jobs/sub_cf.CalibrateEvents_httcp_config_ana__1__4e3cc4e675_946zvuxi2vt/x509up_u10084_6eb055297a

-- setup -------------------------------------------------------------------------------------------

-- bootstrap file
run bootstrap file 'remote_bootstrap_b4f052643c.sh'

source repository setup ...
the CPinHToTauTau analysis was already succesfully setup
re-running the setup requires a new shell
setup failed with code 1
bootstrap file failed (exit code 1), stop job
```

If you can think of any more ideas, please let me know.
Thanks

Best,
Gourab
