### ISSUE TITLE
`all_weights` producer does not have attribute `dataset_inst`

### ISSUE THREAD

**Issue by pkausw** [columnflow/columnflow#428]
After merging #347 , I tried including the changes to an already-existing analysis. After adding the suggested line in the analysis config, I get the following error:

```bash
law run cf.PlotVariables1D --config run2_2017_cms_taupog_nano_v12_limited --dataset tt_sl_powheg --variables jet_pt --version v2 --selector empty --calibrator "" --producer empty --cf.SelectEvents-workflow htcondor
ERROR: luigi-interface - Uncaught exception in luigi
Traceback (most recent call last):
  File "/nfs/dust/cms/user/pkeicher/cf_cache/software/venvs/cf_dev_9b04c75c/lib/python3.9/site-packages/luigi/retcodes.py", line 75, in run_with_retcodes
    worker = luigi.interface._run(argv).worker
  File "/nfs/dust/cms/user/pkeicher/cf_cache/software/venvs/cf_dev_9b04c75c/lib/python3.9/site-packages/luigi/interface.py", line 217, in _run
    return _schedule_and_run([cp.get_task_obj()], worker_scheduler_factory)
  File "/nfs/dust/cms/user/pkeicher/cf_cache/software/venvs/cf_dev_9b04c75c/lib/python3.9/site-packages/luigi/cmdline_parser.py", line 114, in get_task_obj
    return self._get_task_cls()(**self._get_task_kwargs())
  File "/nfs/dust/cms/user/pkeicher/uhh/u4h/hh2bbtautau/modules/columnflow/modules/law/law/task/base.py", line 359, in __call__
    inst = super(Register, cls).__call__(*args, **kwargs)
  File "/nfs/dust/cms/user/pkeicher/cf_cache/software/venvs/cf_dev_9b04c75c/lib/python3.9/site-packages/luigi/task_register.py", line 87, in __call__
    param_values = cls.get_param_values(params, args, kwargs)
  File "/nfs/dust/cms/user/pkeicher/uhh/u4h/hh2bbtautau/modules/columnflow/modules/law/law/task/base.py", line 166, in get_param_values
    for name, value in cls.modify_param_values(OrderedDict(values)).items()
  File "/nfs/dust/cms/user/pkeicher/uhh/u4h/hh2bbtautau/modules/columnflow/columnflow/tasks/framework/base.py", line 767, in modify_param_values
    params = super().modify_param_values(params)
  File "/nfs/dust/cms/user/pkeicher/uhh/u4h/hh2bbtautau/modules/columnflow/columnflow/tasks/framework/base.py", line 93, in modify_param_values
    params = cls.resolve_param_values(params)
  File "/nfs/dust/cms/user/pkeicher/uhh/u4h/hh2bbtautau/modules/columnflow/columnflow/tasks/framework/plotting.py", line 386, in resolve_param_values
    params = super().resolve_param_values(params)
  File "/nfs/dust/cms/user/pkeicher/uhh/u4h/hh2bbtautau/modules/columnflow/columnflow/tasks/framework/mixins.py", line 1768, in resolve_param_values
    params = super().resolve_param_values(params)
  File "/nfs/dust/cms/user/pkeicher/uhh/u4h/hh2bbtautau/modules/columnflow/columnflow/tasks/framework/plotting.py", line 332, in resolve_param_values
    params = super().resolve_param_values(params)
  File "/nfs/dust/cms/user/pkeicher/uhh/u4h/hh2bbtautau/modules/columnflow/columnflow/tasks/framework/mixins.py", line 1890, in resolve_param_values
    params = super().resolve_param_values(params)
  File "/nfs/dust/cms/user/pkeicher/uhh/u4h/hh2bbtautau/modules/columnflow/columnflow/tasks/framework/plotting.py", line 72, in resolve_param_values
    params = super().resolve_param_values(params)
  File "/nfs/dust/cms/user/pkeicher/uhh/u4h/hh2bbtautau/modules/columnflow/columnflow/tasks/framework/mixins.py", line 1711, in resolve_param_values
    params = super().resolve_param_values(params)
  File "/nfs/dust/cms/user/pkeicher/uhh/u4h/hh2bbtautau/modules/columnflow/columnflow/tasks/framework/mixins.py", line 1576, in resolve_param_values
    params = super().resolve_param_values(params)
  File "/nfs/dust/cms/user/pkeicher/uhh/u4h/hh2bbtautau/modules/columnflow/columnflow/tasks/framework/mixins.py", line 2084, in resolve_param_values
    params["weight_producer_inst"] = cls.get_weight_producer_inst(
  File "/nfs/dust/cms/user/pkeicher/uhh/u4h/hh2bbtautau/modules/columnflow/columnflow/tasks/framework/mixins.py", line 2057, in get_weight_producer_inst
    return weight_producer_cls(inst_dict=inst_dict)
  File "/nfs/dust/cms/user/pkeicher/uhh/u4h/hh2bbtautau/modules/columnflow/columnflow/columnar_util.py", line 2138, in __init__
    super().__init__(*args, **kwargs)
  File "/nfs/dust/cms/user/pkeicher/uhh/u4h/hh2bbtautau/modules/columnflow/columnflow/columnar_util.py", line 1613, in __init__
    self.deferred_init(instance_cache=instance_cache)
  File "/nfs/dust/cms/user/pkeicher/uhh/u4h/hh2bbtautau/modules/columnflow/columnflow/columnar_util.py", line 1631, in deferred_init
    self.init_func()
  File "/nfs/dust/cms/user/pkeicher/uhh/u4h/hh2bbtautau/modules/columnflow/columnflow/weight/all_weights.py", line 73, in all_weights_init
    if self.dataset_inst.has_aux("event_weights"):
  File "/nfs/dust/cms/user/pkeicher/uhh/u4h/hh2bbtautau/modules/columnflow/columnflow/columnar_util.py", line 2174, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no attribute '{attr}'")
AttributeError: 'all_weights' object has no attribute 'dataset_inst'
```

Should be an easy fix, but since the PR is already merged in master, I think we should resolve this asap @mafrahm @dsavoiu

**Comment by mafrahm** [comment]
Already fixed, can you pull again and check if it works again?

**Comment by pkausw** [comment]
Jup, works fine, thanks for the quick fix!
