### ISSUE TITLE
Issue in installation of the latest columnflow version

### ISSUE THREAD

**Issue by gsaha009** [columnflow/columnflow#552]
HELP NEEDED BADLY !!!

Hello Experts,

I updated the version of my columnflow recently and while I was trying to do `CF_REINSTALL_SOFTWARE=1 source setup.sh hcp2`, I got the following error,
```sh
┏┏┓┃╻┏┏┳┓┏┓
  ┗┗┛┃┗┛╹┗┗╹┗
    ┏┃
    ╋┃┏┓┓┏┏
    ┛┃┗┛┗┻┛

using variables for setup 'hcp2' from /afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/.setups/hcp2.sh
removing conda setup at /afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/data/software/conda
removing software virtual envs at /afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/data/software/venvs

installing conda with micromamba interface at /afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/data/software/conda
initialized conda with micromamba interface and python 3.9

setting up conda / micromamba environment
critical libmamba filesystem error: cannot set permissions: Permission denied [/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/data/software/conda/pkgs/cache]
setup failed with code 1
```
But I checked that the `cache` dir has right permissions. Any idea would be very helpful

N.B. I can do `source setup.sh hcp2`, but not the re-installation. 
Also sourcing the env is showing the following:
```py
using variables for setup 'hcp' from /afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/.setups/hcp.sh
initialized conda with micromamba interface and python 3.9
/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/modules/columnflow/bin/cf_sandbox_file_hash: line 14: python: command not found
-bash: python: command not found
/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/modules/columnflow/bin/cf_sandbox_file_hash: line 14: python: command not found
-bash: python: command not found
CPinHToTauTau analysis successfully setup
```
Nevertheless, after doing this, if I try to run `selectEvents`, the error I am getting is the following:
```py
WARNING: luigi-interface - Will not run cf.SelectEvents(effective_workflow=local, branch=-1, analysis=httcp.config.analysis_httcp.analysis_httcp, version=Oct22_v2, config=run3_2022_preEE_nano_cp_tau_v12_limited, shift=nominal, local_shift=nominal, dataset=h_ggf_tautau_uncorrelated_filter, calibrators=main, selector=main, workflow=local) or any dependencies due to error in complete() method:
Traceback (most recent call last):
  File "/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/data/software/venvs/cf_dev_/lib64/python3.9/site-packages/luigi/worker.py", line 441, in check_complete
    is_complete = check_complete_cached(task, completion_cache)
  File "/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/data/software/venvs/cf_dev_/lib64/python3.9/site-packages/luigi/worker.py", line 426, in check_complete_cached
    is_complete = task.complete()
  File "/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/modules/columnflow/modules/law/law/workflow/base.py", line 114, in complete
    return super(BaseWorkflowProxy, self).complete()
  File "/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/modules/columnflow/modules/law/law/task/base.py", line 231, in complete
    return all(t.complete() for t in outputs)
  File "/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/modules/columnflow/modules/law/law/task/base.py", line 231, in <genexpr>
    return all(t.complete() for t in outputs)
  File "/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/modules/columnflow/modules/law/law/target/collection.py", line 146, in complete
    return self.optional or self.exists(**kwargs)
  File "/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/modules/columnflow/modules/law/law/target/collection.py", line 160, in exists
    for i, _ in enumerate(self.iter_existing(**kwargs)):
  File "/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/modules/columnflow/modules/law/law/target/collection.py", line 340, in _iter_state
    if not self.dir.exists():
  File "/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/modules/columnflow/modules/law/law/target/file.py", line 230, in exists
    return self.fs.exists(self.path, **kwargs)
  File "/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/modules/columnflow/modules/law/law/target/remote/base.py", line 201, in exists
    return self.file_interface.exists(self.abspath(path), stat=stat, **kwargs)
  File "/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/modules/columnflow/modules/law/law/contrib/gfal/target.py", line 130, in exists
    with self.context() as ctx:
  File "/usr/lib64/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/modules/columnflow/modules/law/law/contrib/gfal/target.py", line 100, in context
    self._contexts[pid] = ctx = gfal2.creat_context()
  File "/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/modules/columnflow/modules/law/law/contrib/gfal/target.py", line 39, in __getattr__
    raise Exception("trying to access 'gfal2.{}', but gfal2 is not installed".format(attr))
Exception: trying to access 'gfal2.creat_context', but gfal2 is not installed
```

It looks like a complete mess at my end.. I just tried to update the latest version as I have been working on an old commit. If you guys could kindly suggest something, it would be really great.

Repo: https://github.com/gsaha009/CPinHToTauTau/tree/dev
workarea: `/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau`

Thanks 

Best,
Gourab

**Comment by gsaha009** [comment]
The problem is apparently with `afs` only. I have found that the software can be installed successfully in `eos`, also I could run it locally, but the problem is again with the `HTCondor`

If there is a set of instructions available to set the software up in lxplus, it would very helpful. 
My `.setups/hcp.sh` looks like the following:

```sh
export CF_CERN_USER="gsaha"
export CF_CERN_USER_FIRSTCHAR="${CF_CERN_USER:0:1}"
export CF_DATA="/eos/user/g/gsaha/CPinHToTauTauOutput"
export CF_SOFTWARE_BASE="$CF_DATA/software"
export CF_JOB_BASE="./data/jobs"
export CF_STORE_NAME="cf_store"
export CF_STORE_LOCAL="$CF_DATA/$CF_STORE_NAME"
export CF_WLCG_CACHE_ROOT=""
export CF_WLCG_USE_CACHE="false"
export CF_WLCG_CACHE_CLEANUP="false"
export CF_VENV_SETUP_MODE_UPDATE="False"
export CF_VENV_SETUP_MODE="update"
export CF_LOCAL_SCHEDULER="True"
export CF_SCHEDULER_HOST="127.0.0.1"
export CF_SCHEDULER_PORT="8082"
export CF_FLAVOR="cms"
export CF_CRAB_STORAGE_ELEMENT="T2_FR_IPHC"
export CF_CRAB_BASE_DIRECTORY="/store/user/$CF_CERN_USER/cf_crab_outputs"
```

The error I am having while trying to send jobs to condor is the following:

```sh
INFO: luigi-interface - [pid 2029110] Worker Worker(salt=5874309394, workers=1, host=lxplus935.cern.ch, username=gsaha, pid=2029110) running   cf.CalibrateEvents(effective_workflow=htcondor, branch=-1, analysis=httcp.config.analysis_httcp.analysis_httcp, version=Oct23_v5, config=run3_2022_preEE_nano_cp_tau_v12_limited, shift=nominal, local_shift=nominal, dataset=h_ggf_tautau_uncorrelated_filter, calibrator=main, workflow=htcondor)
going to submit 1 htcondor job(s), run3_2022_preEE_nano_cp_tau_v12_limited, h_ggf_tautau_uncorrelated_filter
ERROR: luigi-interface - [pid 2029110] Worker Worker(salt=5874309394, workers=1, host=lxplus935.cern.ch, username=gsaha, pid=2029110) failed    cf.CalibrateEvents(effective_workflow=htcondor, branch=-1, analysis=httcp.config.analysis_httcp.analysis_httcp, version=Oct23_v5, config=run3_2022_preEE_nano_cp_tau_v12_limited, shift=nominal, local_shift=nominal, dataset=h_ggf_tautau_uncorrelated_filter, calibrator=main, workflow=htcondor)
Traceback (most recent call last):
  File "/eos/user/g/gsaha/CPinHToTauTauOutput/software/venvs/cf_dev_9b04c75c/lib/python3.9/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/eos/user/g/gsaha/CPinHToTauTauOutput/software/venvs/cf_dev_9b04c75c/lib/python3.9/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/modules/columnflow/modules/law/law/workflow/remote.py", line 628, in run
    return self._run_impl()
  File "/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/modules/columnflow/modules/law/law/workflow/remote.py", line 700, in _run_impl
    self.submit()
  File "/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/modules/columnflow/modules/law/law/workflow/remote.py", line 882, in submit
    job_ids, submission_data = self._submit_group(submit_jobs)
  File "/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/modules/columnflow/modules/law/law/contrib/htcondor/workflow.py", line 190, in _submit_group
    c, p = job_id.split(".")
AttributeError: 'Exception' object has no attribute 'split'
INFO: luigi-interface - Informed scheduler that task   cf.CalibrateEvents_httcp_config_ana__1__f25b583b5f   has status   FAILED
INFO: luigi-interface - Worker Worker(salt=5874309394, workers=1, host=lxplus935.cern.ch, username=gsaha, pid=2029110) was stopped. Shutting down Keep-Alive thread
INFO: luigi-interface - 
===== Luigi Execution Summary =====
```
here you can find the condor failed information in details: 
`/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/data/jobs/sub_cf.CalibrateEvents_httcp_config_ana__1__f25b583b5f_483it21gubs`

We, from IPHC, have been struggling with this setup in `lxplus` for quite a while. It was working once, if we keep everything in `afs`, and then just mention the output per task in `eos` through `law.cfg`. But, now the software needs to be installed in `eos`, and that is why I have kept the jobs directory in my `afs` intentionally. However, it is still not working for `HTCondor`.

I would request you to have a look and just try it out entirely on `lxplus` as well. If it has already been verified, could you please point me to the instructions?
Thanks a lot.

best,
Gourab (cc. @oponcet)

**Comment by pkausw** [comment]
Ho @gsaha009 ,

thanks for opening this issue and following up on the installation issue. Indeed, it seems like you cannot install anything with micromamba in /afs/ on lxplus at the moment. The workaround is as you have outlined it - set the `CF_SOFTWARE_BASE` argument to an eos directory and it should work again.

The issue you mentioned with htcondor on lxplus is new, and unrelated to the issue with micromamba on lxplus. Therefore, I'll close this issue and open a new one (also tagging you there). We are in the process of understand what has changed and how to fix it again. We hope we can resolve this fast, sorry for the inconvenience.

Cheers,
Philip
