### ISSUE TITLE
HTCondor not working on lxplus

### ISSUE THREAD

**Issue by pkausw** [columnflow/columnflow#554]
As pointed out by @gsaha009 in issue #552 , htcondor is currently not working on lxplus.
Since this issue is unrelated to the original topic of #552, I'm moving the information in the other thread here.

Here is the error trace that @gsaha009 has provided:

```
INFO: luigi-interface - [pid 2029110] Worker Worker(salt=5874309394, workers=1, host=lxplus935.cern.ch, username=gsaha, pid=2029110) running   cf.CalibrateEvents(effective_workflow=htcondor, branch=-1, analysis=httcp.config.analysis_httcp.analysis_httcp, version=Oct23_v5, config=run3_2022_preEE_nano_cp_tau_v12_limited, shift=nominal, local_shift=nominal, dataset=h_ggf_tautau_uncorrelated_filter, calibrator=main, workflow=htcondor)
going to submit 1 htcondor job(s), run3_2022_preEE_nano_cp_tau_v12_limited, h_ggf_tautau_uncorrelated_filter
ERROR: luigi-interface - [pid 2029110] Worker Worker(salt=5874309394, workers=1, host=lxplus935.cern.ch, username=gsaha, pid=2029110) failed    cf.CalibrateEvents(effective_workflow=htcondor, branch=-1, analysis=httcp.config.analysis_httcp.analysis_httcp, version=Oct23_v5, config=run3_2022_preEE_nano_cp_tau_v12_limited, shift=nominal, local_shift=nominal, dataset=h_ggf_tautau_uncorrelated_filter, calibrator=main, workflow=htcondor)
Traceback (most recent call last):
  File "/eos/user/g/gsaha/CPinHToTauTauOutput/software/venvs/cf_dev_9b04c75c/lib/python3.9/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/eos/user/g/gsaha/CPinHToTauTauOutput/software/venvs/cf_dev_9b04c75c/lib/python3.9/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/modules/columnflow/modules/law/law/workflow/remote.py", line 628, in run
    return self._run_impl()
  File "/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/modules/columnflow/modules/law/law/workflow/remote.py", line 700, in _run_impl
    self.submit()
  File "/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/modules/columnflow/modules/law/law/workflow/remote.py", line 882, in submit
    job_ids, submission_data = self._submit_group(submit_jobs)
  File "/afs/cern.ch/work/g/gsaha/public/IPHC/Work/ColumnFlowAnalyses/CPinHToTauTau/modules/columnflow/modules/law/law/contrib/htcondor/workflow.py", line 190, in _submit_group
    c, p = job_id.split(".")
AttributeError: 'Exception' object has no attribute 'split'
INFO: luigi-interface - Informed scheduler that task   cf.CalibrateEvents_httcp_config_ana__1__f25b583b5f   has status   FAILED
INFO: luigi-interface - Worker Worker(salt=5874309394, workers=1, host=lxplus935.cern.ch, username=gsaha, pid=2029110) was stopped. Shutting down Keep-Alive thread
INFO: luigi-interface - 
===== Luigi Execution Summary =====
```

**Comment by gsaha009** [comment]
Thanks @pkausw for making it high priority.
I just wanted to add that I have managed to bypass this error by [this](https://github.com/gsaha009/CPinHToTauTau/blob/main/README.md) strategy.
I have checked that the jobs are running both locally and on HTCondor. Only caveat is that, the parquet or pickle i.e. the big files are being saved in `eos` as expected, but all other output are in `afs`.

**Comment by pkausw** [comment]
Hi @gsaha009 , @riga pushed a fix for this issue in law: https://github.com/riga/law/commit/3a8a1651ee20d3c54a8e3611baddf01bb0cfb840. Can you update to the latest master version of cf (commit [273b0ba](https://github.com/columnflow/columnflow/commit/273b0ba7049e4999b742910ab53a67ad94526233)) and try again?

**Comment by pkausw** [comment]
This issue is fixed when using the following configuration:

- change output location to `wlcg` targets (example for lxplus eos can be found in [columnflow tutorial](https://gitlab.cern.ch/cms-analysis/analysisexamples/columnflow-demo/-/blob/master/law.cfg?ref_type=heads#L112)
- `CF_JOB_DATA` and `CF_DATA` should point to directories on `afs`
- (unrelated to htcondor, but still specific to lxplus/DESY setups:) `CF_SOFTWARE_BASE` should not point to `afs` (e.g. to eos)
